services:
  jenkins-shared-lib-test:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    user: "${UID}:${GID}"
    volumes:
      - ./build-docker:/app/build
    command: >
      gradle test
      --no-daemon
      --info
